In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import numpy as np

# merging Video data files and text data for crct order of videos

In [ ]:
df1=pd.read_csv('/content/drive/MyDrive/video_d')

In [ ]:
df=pd.read_csv('/content/drive/MyDrive/text/MU3D Codebook.xlsx - Video-Level Data.csv')
#df.VideoID.unique()

In [ ]:
df

,VideoID,Valence,Veracity,Sex,Race,VidLength_ms,VidLength_sec,WordCount,Accuracy,TruthProp,Attractive,Trustworthy,Anxious,Transcription
0,BF001_1PT,1,1,0,0,38783,38.78,110,0.77,0.77,4.55,4.32,3.18,My best friend is a really nice person. Um. Sh...
1,BF001_2NL,0,0,0,0,37120,37.12,88,0.40,0.60,3.55,3.75,3.05,She’s actually really two faced and not fun to...
2,BF001_3NT,0,1,0,0,38484,38.48,120,0.77,0.77,3.27,3.95,2.82,So this specific person is actually just a rea...
3,BF001_4PL,1,0,0,0,38026,38.03,124,0.58,0.42,4.05,4.05,3.11,This person is actually a really kind person. ...
4,BF002_1PT,1,1,0,0,36351,36.35,91,0.59,0.59,4.86,4.36,3.32,My roommate is a really good person. She’s ver...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
315,WM026_4PL,1,0,1,1,41899,41.90,102,0.50,0.50,4.15,4.20,3.55,He’s a really good guy. Uh. He’s always cleani...
316,WM027_1PT,1,1,1,1,33732,33.73,86,0.47,0.47,4.26,4.11,1.79,My roommate is a great guy. There is many grea...
317,WM027_2NL,0,0,1,1,41566,41.57,87,0.45,0.55,3.82,4.27,2.55,"My roommate is insufferable. He is, uh, comple..."
318,WM027_3NT,0,1,1,1,32132,32.13,84,0.50,0.50,4.18,4.32,3.00,My cousin is a terrible person. She makes me r...
319,WM027_4PL,1,0,1,1,36932,36.93,109,0.18,0.82,3.95,4.68,2.23,I have a cousin who can literally make me smil...

In [ ]:
df1 = df1.replace({'VideoID': {'WM19_4PL': 'WM019_4PL','WM13_3NT':'WM013_3NT','WM19_3NT':'WM019_3NT','WM001_PT':'WM001_1PT'}})

In [ ]:
df1[df1['tag'].str.startswith('WM001')]

,Unnamed: 0,video_name,tag,VideoID
231,231,/content/drive/MyDrive/Videos/Videos/WM001_2NL...,WM001_2NL.wmv,WM001_2NL
239,239,/content/drive/MyDrive/Videos/Videos/WM001_3NT...,WM001_3NT.wmv,WM001_3NT
245,245,/content/drive/MyDrive/Videos/Videos/WM001_PT.wmv,WM001_PT.wmv,WM001_1PT
246,246,/content/drive/MyDrive/Videos/Videos/WM001_4PL...,WM001_4PL.wmv,WM001_4PL

In [ ]:
df[df['VideoID'].str.startswith('WM001')]

,VideoID,Valence,Veracity,Sex,Race,VidLength_ms,VidLength_sec,WordCount,Accuracy,TruthProp,Attractive,Trustworthy,Anxious,Transcription
240,WM001_1PT,1,1,1,1,31932,31.93,76,0.25,0.25,3.05,2.90,3.95,He is a year older than me and I met him when ...
241,WM001_2NL,0,0,1,1,28466,28.47,61,0.55,0.45,3.23,3.68,4.32,"Someone who often takes, uh, the easy way out ..."
242,WM001_3NT,0,1,1,1,25732,25.73,70,0.25,0.25,3.65,3.45,3.85,He attends the University of Cincinnati. I wen...
243,WM001_4PL,1,0,1,1,31599,31.60,85,0.55,0.45,3.30,3.40,4.45,He’s a really honest person which is obviously...

In [ ]:
df.VideoID.unique()

array(['BF001_1PT', 'BF001_2NL', 'BF001_3NT', 'BF001_4PL', 'BF002_1PT',
       'BF002_2NL', 'BF002_3NT', 'BF002_4PL', 'BF003_1PT', 'BF003_2NL',
       'BF003_3NT', 'BF003_4PL', 'BF004_1PT', 'BF004_2NL', 'BF004_3NT',
       'BF004_4PL', 'BF006_1PT', 'BF006_2NL', 'BF006_3NT', 'BF006_4PL',
       'BF008_1PT', 'BF008_2NL', 'BF008_3NT', 'BF008_4PL', 'BF013_1PT',
       'BF013_2NL', 'BF013_3NT', 'BF013_4PL', 'BF014_1PT', 'BF014_2NL',
       'BF014_3NT', 'BF014_4PL', 'BF015_1PT', 'BF015_2NL', 'BF015_3NT',
       'BF015_4PL', 'BF016_1PT', 'BF016_2NL', 'BF016_3NT', 'BF016_4PL',
       'BF018_1PT', 'BF018_2NL', 'BF018_3NT', 'BF018_4PL', 'BF019_1PT',
       'BF019_2NL', 'BF019_3NT', 'BF019_4PL', 'BF020_1PT', 'BF020_2NL',
       'BF020_3NT', 'BF020_4PL', 'BF022_1PT', 'BF022_2NL', 'BF022_3NT',
       'BF022_4PL', 'BF023_1PT', 'BF023_2NL', 'BF023_3NT', 'BF023_4PL',
       'BF024_1PT', 'BF024_2NL', 'BF024_3NT', 'BF024_4PL', 'BF025_1PT',
       'BF025_2NL', 'BF025_3NT', 'BF025_4PL', 'BF027_1PT', 'BF027_2NL',
       'BF027_3NT', 'BF027_4PL', 'BF028_1PT', 'BF028_2NL', 'BF028_3NT',
       'BF028_4PL', 'BF033_1PT', 'BF033_2NL', 'BF033_3NT', 'BF033_4PL',
       'BM003_1PT', 'BM003_2NL', 'BM003_3NT', 'BM003_4PL', 'BM004_1PT',
       'BM004_2NL', 'BM004_3NT', 'BM004_4PL', 'BM005_1PT', 'BM005_2NL',
       'BM005_3NT', 'BM005_4PL', 'BM006_1PT', 'BM006_2NL', 'BM006_3NT',
       'BM006_4PL', 'BM007_1PT', 'BM007_2NL', 'BM007_3NT', 'BM007_4PL',
       'BM008_1PT', 'BM008_2NL', 'BM008_3NT', 'BM008_4PL', 'BM009_1PT',
       'BM009_2NL', 'BM009_3NT', 'BM009_4PL', 'BM010_1PT', 'BM010_2NL',
       'BM010_3NT', 'BM010_4PL', 'BM012_1PT', 'BM012_2NL', 'BM012_3NT',
       'BM012_4PL', 'BM013_1PT', 'BM013_2NL', 'BM013_3NT', 'BM013_4PL',
       'BM014_1PT', 'BM014_2NL', 'BM014_3NT', 'BM014_4PL', 'BM015_1PT',
       'BM015_2NL', 'BM015_3NT', 'BM015_4PL', 'BM016_1PT', 'BM016_2NL',
       'BM016_3NT', 'BM016_4PL', 'BM017_1PT', 'BM017_2NL', 'BM017_3NT',
       'BM017_4PL', 'BM018_1PT', 'BM018_2NL', 'BM018_3NT', 'BM018_4PL',
       'BM020_1PT', 'BM020_2NL', 'BM020_3NT', 'BM020_4PL', 'BM021_1PT',
       'BM021_2NL', 'BM021_3NT', 'BM021_4PL', 'BM024_1PT', 'BM024_2NL',
       'BM024_3NT', 'BM024_4PL', 'BM026_1PT', 'BM026_2NL', 'BM026_3NT',
       'BM026_4PL', 'BM027_1PT', 'BM027_2NL', 'BM027_3NT', 'BM027_4PL',
       'WF002_1PT', 'WF002_2NL', 'WF002_3NT', 'WF002_4PL', 'WF003_1PT',
       'WF003_2NL', 'WF003_3NT', 'WF003_4PL', 'WF005_1PT', 'WF005_2NL',
       'WF005_3NT', 'WF005_4PL', 'WF006_1PT', 'WF006_2NL', 'WF006_3NT',
       'WF006_4PL', 'WF007_1PT', 'WF007_2NL', 'WF007_3NT', 'WF007_4PL',
       'WF009_1PT', 'WF009_2NL', 'WF009_3NT', 'WF009_4PL', 'WF010_1PT',
       'WF010_2NL', 'WF010_3NT', 'WF010_4PL', 'WF011_1PT', 'WF011_2NL',
       'WF011_3NT', 'WF011_4PL', 'WF012_1PT', 'WF012_2NL', 'WF012_3NT',
       'WF012_4PL', 'WF013_1PT', 'WF013_2NL', 'WF013_3NT', 'WF013_4PL',
       'WF014_1PT', 'WF014_2NL', 'WF014_3NT', 'WF014_4PL', 'WF016_1PT',
       'WF016_2NL', 'WF016_3NT', 'WF016_4PL', 'WF017_1PT', 'WF017_2NL',
       'WF017_3NT', 'WF017_4PL', 'WF018_1PT', 'WF018_2NL', 'WF018_3NT',
       'WF018_4PL', 'WF019_1PT', 'WF019_2NL', 'WF019_3NT', 'WF019_4PL',
       'WF021_1PT', 'WF021_2NL', 'WF021_3NT', 'WF021_4PL', 'WF022_1PT',
       'WF022_2NL', 'WF022_3NT', 'WF022_4PL', 'WF023_1PT', 'WF023_2NL',
       'WF023_3NT', 'WF023_4PL', 'WF024_1PT', 'WF024_2NL', 'WF024_3NT',
       'WF024_4PL', 'WF025_1PT', 'WF025_2NL', 'WF025_3NT', 'WF025_4PL',
       'WM001_1PT', 'WM001_2NL', 'WM001_3NT', 'WM001_4PL', 'WM002_1PT',
       'WM002_2NL', 'WM002_3NT', 'WM002_4PL', 'WM005_1PT', 'WM005_2NL',
       'WM005_3NT', 'WM005_4PL', 'WM006_1PT', 'WM006_2NL', 'WM006_3NT',
       'WM006_4PL', 'WM007_1PT', 'WM007_2NL', 'WM007_3NT', 'WM007_4PL',
       'WM008_1PT', 'WM008_2NL', 'WM008_3NT', 'WM008_4PL', 'WM009_1PT',
       'WM009_2NL', 'WM009_3NT', 'WM009_4PL', 'WM011_1PT', 'WM011_2NL',
       'WM011_3NT', 'WM011_4PL', 'WM013_1PT', 'WM013_2NL', 'WM013_3NT',
       'WM013_4PL', 'WM014_1PT', 'WM014_2NL', 'WM014_3NT', 'WM014_4PL',
       'WM016_1PT', 'WM016_2NL', 'WM016_3NT', 'WM016_4PL', 'WM017_1PT',
       'WM017_2NL', 'WM017_3NT', 'WM017_4PL', 'WM018_1PT', 'WM018_2NL',
       'WM018_3NT', 'WM018_4PL', 'WM019_1PT', 'WM019_2NL', 'WM019_3NT',
       'WM019_4PL', 'WM020_1PT', 'WM020_2NL', 'WM020_3NT', 'WM020_4PL',
       'WM021_1PT', 'WM021_2NL', 'WM021_3NT', 'WM021_4PL', 'WM022_1PT',
       'WM022_2NL', 'WM022_3NT', 'WM022_4PL', 'WM024_1PT', 'WM024_2NL',
       'WM024_3NT', 'WM024_4PL', 'WM026_1PT', 'WM026_2NL', 'WM026_3NT',
       'WM026_4PL', 'WM027_1PT', 'WM027_2NL', 'WM027_3NT', 'WM027_4PL'],
      dtype=object)

In [ ]:
df.isna().sum()
df.nunique()

VideoID          320
Valence            2
Veracity           2
Sex                2
Race               2
VidLength_ms     258
VidLength_sec    232
WordCount         98
Accuracy          67
TruthProp         62
Attractive       133
Trustworthy      127
Anxious          139
Transcription    320
dtype: int64

In [ ]:
Max_count=max(df.WordCount)

In [ ]:
max_count_row = df[df['WordCount'] == Max_count]
max_count_row

,VideoID,Valence,Veracity,Sex,Race,VidLength_ms,VidLength_sec,WordCount,Accuracy,TruthProp,Attractive,Trustworthy,Anxious,Transcription
232,WF024_1PT,1,1,0,1,36362,36.36,160,0.86,0.86,3.86,4.52,3.38,I met her through my uh friend my from high sc...

In [ ]:
df1

,Unnamed: 0,video_name,tag,VideoID
0,0,/content/drive/MyDrive/Videos/Videos/BF003_3NT...,BF003_3NT.wmv,BF003_3NT
1,1,/content/drive/MyDrive/Videos/Videos/BF001_4PL...,BF001_4PL.wmv,BF001_4PL
2,2,/content/drive/MyDrive/Videos/Videos/BF001_1PT...,BF001_1PT.wmv,BF001_1PT
3,3,/content/drive/MyDrive/Videos/Videos/BF003_4PL...,BF003_4PL.wmv,BF003_4PL
4,4,/content/drive/MyDrive/Videos/Videos/BF002_3NT...,BF002_3NT.wmv,BF002_3NT
...,...,...,...,...
315,315,/content/drive/MyDrive/Videos/Videos/WM13_3NT.wmv,WM13_3NT.wmv,WM013_3NT
316,316,/content/drive/MyDrive/Videos/Videos/WM19_3NT.wmv,WM19_3NT.wmv,WM019_3NT
317,317,/content/drive/MyDrive/Videos/Videos/WM19_4PL.wmv,WM19_4PL.wmv,WM019_4PL
318,318,/content/drive/MyDrive/Videos/Videos/WM027_3NT...,WM027_3NT.wmv,WM027_3NT
319,319,/content/drive/MyDrive/Videos/Videos/WM027_4PL...,WM027_4PL.wmv,WM027_4PL

In [ ]:
merged_df = pd.merge(df1, df, on='VideoID',how='inner')

In [ ]:
merged_df

,Unnamed: 0,video_name,tag,VideoID,Valence,Veracity,Sex,Race,VidLength_ms,VidLength_sec,WordCount,Accuracy,TruthProp,Attractive,Trustworthy,Anxious,Transcription
0,0,/content/drive/MyDrive/Videos/Videos/BF003_3NT...,BF003_3NT.wmv,BF003_3NT,0,1,0,0,35338,35.34,85,0.71,0.71,3.24,4.76,2.24,"She is so rude to everybody: students, teacher..."
1,1,/content/drive/MyDrive/Videos/Videos/BF001_4PL...,BF001_4PL.wmv,BF001_4PL,1,0,0,0,38026,38.03,124,0.58,0.42,4.05,4.05,3.11,This person is actually a really kind person. ...
2,2,/content/drive/MyDrive/Videos/Videos/BF001_1PT...,BF001_1PT.wmv,BF001_1PT,1,1,0,0,38783,38.78,110,0.77,0.77,4.55,4.32,3.18,My best friend is a really nice person. Um. Sh...
3,3,/content/drive/MyDrive/Videos/Videos/BF003_4PL...,BF003_4PL.wmv,BF003_4PL,1,0,0,0,28896,28.90,128,0.47,0.53,3.00,4.21,2.74,"She is an angel. Ha. I know, I can’t, it’s wei..."
4,4,/content/drive/MyDrive/Videos/Videos/BF002_3NT...,BF002_3NT.wmv,BF002_3NT,0,1,0,0,29141,29.14,95,0.60,0.60,4.40,4.50,3.15,"This person is very rude, she makes snide comm..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
315,315,/content/drive/MyDrive/Videos/Videos/WM13_3NT.wmv,WM13_3NT.wmv,WM013_3NT,0,1,1,1,34766,34.77,128,0.74,0.74,3.57,4.00,3.22,"Um, she went to grade school with me. We’re st..."
316,316,/content/drive/MyDrive/Videos/Videos/WM19_3NT.wmv,WM19_3NT.wmv,WM019_3NT,0,1,1,1,40132,40.13,148,0.43,0.43,3.62,3.24,3.52,I have this one kid in my fraternity who might...
317,317,/content/drive/MyDrive/Videos/Videos/WM19_4PL.wmv,WM19_4PL.wmv,WM019_4PL,1,0,1,1,34566,34.57,115,0.63,0.37,4.00,3.47,3.42,"He, uh, he’s from Ohio actually so, he’s a lit..."
318,318,/content/drive/MyDrive/Videos/Videos/WM027_3NT...,WM027_3NT.wmv,WM027_3NT,0,1,1,1,32132,32.13,84,0.50,0.50,4.18,4.32,3.00,My cousin is a terrible person. She makes me r...
319,319,/content/drive/MyDrive/Videos/Videos/WM027_4PL...,WM027_4PL.wmv,WM027_4PL,1,0,1,1,36932,36.93,109,0.18,0.82,3.95,4.68,2.23,I have a cousin who can literally make me smil...

In [ ]:
merged_df.nunique(),df.nunique()

(Unnamed: 0       320
 video_name       320
 tag              320
 VideoID          320
 Valence            2
 Veracity           2
 Sex                2
 Race               2
 VidLength_ms     258
 VidLength_sec    232
 WordCount         98
 Accuracy          67
 TruthProp         62
 Attractive       133
 Trustworthy      127
 Anxious          139
 Transcription    320
 dtype: int64,
 VideoID          320
 Valence            2
 Veracity           2
 Sex                2
 Race               2
 VidLength_ms     258
 VidLength_sec    232
 WordCount         98
 Accuracy          67
 TruthProp         62
 Attractive       133
 Trustworthy      127
 Anxious          139
 Transcription    320
 dtype: int64)

In [ ]:
merged_df.shape

(320, 17)

In [ ]:
df1

,Unnamed: 0,video_name,tag,VideoID
0,0,/content/drive/MyDrive/Videos/Videos/BF003_3NT...,BF003_3NT.wmv,BF003_3NT
1,1,/content/drive/MyDrive/Videos/Videos/BF001_4PL...,BF001_4PL.wmv,BF001_4PL
2,2,/content/drive/MyDrive/Videos/Videos/BF001_1PT...,BF001_1PT.wmv,BF001_1PT
3,3,/content/drive/MyDrive/Videos/Videos/BF003_4PL...,BF003_4PL.wmv,BF003_4PL
4,4,/content/drive/MyDrive/Videos/Videos/BF002_3NT...,BF002_3NT.wmv,BF002_3NT
...,...,...,...,...
315,315,/content/drive/MyDrive/Videos/Videos/WM13_3NT.wmv,WM13_3NT.wmv,WM013_3NT
316,316,/content/drive/MyDrive/Videos/Videos/WM19_3NT.wmv,WM19_3NT.wmv,WM019_3NT
317,317,/content/drive/MyDrive/Videos/Videos/WM19_4PL.wmv,WM19_4PL.wmv,WM019_4PL
318,318,/content/drive/MyDrive/Videos/Videos/WM027_3NT...,WM027_3NT.wmv,WM027_3NT
319,319,/content/drive/MyDrive/Videos/Videos/WM027_4PL...,WM027_4PL.wmv,WM027_4PL

In [ ]:
df.Transcription

0      My best friend is a really nice person. Um. Sh...
1      She’s actually really two faced and not fun to...
2      So this specific person is actually just a rea...
3      This person is actually a really kind person. ...
4      My roommate is a really good person. She’s ver...
                             ...
315    He’s a really good guy. Uh. He’s always cleani...
316    My roommate is a great guy. There is many grea...
317    My roommate is insufferable. He is, uh, comple...
318    My cousin is a terrible person. She makes me r...
319    I have a cousin who can literally make me smil...
Name: Transcription, Length: 320, dtype: object

In [ ]:
merged_df=merged_df.drop(['Sex',	'Race',	'VidLength_ms',	'VidLength_sec',	'WordCount','Trustworthy','TruthProp'	,'Attractive'],axis=1)

#preprocessing the merged data for model buiding(Basic Neural Network)

In [ ]:
import nltk
from keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [ ]:
merged_df

,Unnamed: 0,video_name,tag,VideoID,Valence,Veracity,Accuracy,Anxious,Transcription
0,0,/content/drive/MyDrive/Videos/Videos/BF003_3NT...,BF003_3NT.wmv,BF003_3NT,0,1,0.71,2.24,"She is so rude to everybody: students, teacher..."
1,1,/content/drive/MyDrive/Videos/Videos/BF001_4PL...,BF001_4PL.wmv,BF001_4PL,1,0,0.58,3.11,This person is actually a really kind person. ...
2,2,/content/drive/MyDrive/Videos/Videos/BF001_1PT...,BF001_1PT.wmv,BF001_1PT,1,1,0.77,3.18,My best friend is a really nice person. Um. Sh...
3,3,/content/drive/MyDrive/Videos/Videos/BF003_4PL...,BF003_4PL.wmv,BF003_4PL,1,0,0.47,2.74,"She is an angel. Ha. I know, I can’t, it’s wei..."
4,4,/content/drive/MyDrive/Videos/Videos/BF002_3NT...,BF002_3NT.wmv,BF002_3NT,0,1,0.60,3.15,"This person is very rude, she makes snide comm..."
...,...,...,...,...,...,...,...,...,...
315,315,/content/drive/MyDrive/Videos/Videos/WM13_3NT.wmv,WM13_3NT.wmv,WM013_3NT,0,1,0.74,3.22,"Um, she went to grade school with me. We’re st..."
316,316,/content/drive/MyDrive/Videos/Videos/WM19_3NT.wmv,WM19_3NT.wmv,WM019_3NT,0,1,0.43,3.52,I have this one kid in my fraternity who might...
317,317,/content/drive/MyDrive/Videos/Videos/WM19_4PL.wmv,WM19_4PL.wmv,WM019_4PL,1,0,0.63,3.42,"He, uh, he’s from Ohio actually so, he’s a lit..."
318,318,/content/drive/MyDrive/Videos/Videos/WM027_3NT...,WM027_3NT.wmv,WM027_3NT,0,1,0.50,3.00,My cousin is a terrible person. She makes me r...
319,319,/content/drive/MyDrive/Videos/Videos/WM027_4PL...,WM027_4PL.wmv,WM027_4PL,1,0,0.18,2.23,I have a cousin who can literally make me smil...

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
#it is simpler option to take first k vocabularies and simpler to computation but most of the important words will be misse
tokenizer = Tokenizer( oov_token='<OOV>')
tokenizer.fit_on_texts(merged_df['Transcription'])
sequences = tokenizer.texts_to_sequences(merged_df['Transcription'])
padded_sequences = pad_sequences(sequences, maxlen=Max_count, padding='post', truncating='post')

In [ ]:
padded_sequences,padded_sequences.shape

(array([[  10,   24,   25, ...,    0,    0,    0],
        [  34,   29,   24, ...,    0,    0,    0],
        [  23,   79,   69, ...,    0,    0,    0],
        ...,
        [   9,   27,   28, ...,    0,    0,    0],
        [  23, 1340,   24, ...,    0,    0,    0],
        [   3,   41,    7, ...,    0,    0,    0]], dtype=int32),
 (320, 160))

#Simple forward neural network

In [ ]:
from keras.backend import dropout
import tensorflow as tf

# Create a sequential model
model = tf.keras.Sequential()

# Add input layer
model.add(tf.keras.layers.Input(shape=(163,)))

# Add fully connected hidden layers with ReLU activation
model.add(tf.keras.layers.Dense(128, activation='tanh'))
model.add(tf.keras.layers.Dropout(0.2))

model.add(tf.keras.layers.Dense(64, activation='tanh'))

model.add(tf.keras.layers.Dense(32, activation='tanh'))
model.add(tf.keras.layers.Dropout(0.3))
# Add output layer with sigmoid activation
model.add(tf.keras.layers.Dense(1, activation='tanh'))
model.summary()

Model: "sequential_12"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_19 (Dense)            (None, 128)               20992

 dropout_2 (Dropout)         (None, 128)               0

 dense_20 (Dense)            (None, 64)                8256

 dense_21 (Dense)            (None, 32)                2080

 dropout_3 (Dropout)         (None, 32)                0

 dense_22 (Dense)            (None, 1)                 33

=================================================================
Total params: 31,361
Trainable params: 31,361
Non-trainable params: 0
_________________________________________________________________

In [ ]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
labels=df.Veracity.to_list()
labels=np.array(labels)
accuracy_tr=np.array(df.Accuracy)
anxious=np.array(df.Anxious)
valence=np.array(df.Valence)
accuracy_tr=accuracy_tr.reshape(320,1)
anxious=anxious.reshape(320,1)
valence=valence.reshape(320,1)

In [ ]:
concatenated_data = np.concatenate([padded_sequences,accuracy_tr, anxious,valence], axis=1)
concatenated_data.shape,padded_sequences.shape

((320, 163), (320, 160))

In [ ]:
### Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(concatenated_data,labels,test_size=0.2,random_state=0)

In [ ]:
X_train.shape,y_train.shape

((256, 163), (256,))

In [ ]:
model.fit(X_train,y_train,epochs=20)

Epoch 1/20
8/8 [==============================] - 1s 4ms/step - loss: 2.9579 - accuracy: 0.5273
Epoch 2/20
8/8 [==============================] - 0s 3ms/step - loss: 2.8866 - accuracy: 0.4805
Epoch 3/20
8/8 [==============================] - 0s 2ms/step - loss: 2.2888 - accuracy: 0.5469
Epoch 4/20
8/8 [==============================] - 0s 2ms/step - loss: 2.2162 - accuracy: 0.5586
Epoch 5/20
8/8 [==============================] - 0s 2ms/step - loss: 1.9394 - accuracy: 0.5508
Epoch 6/20
8/8 [==============================] - 0s 3ms/step - loss: 2.2583 - accuracy: 0.5430
Epoch 7/20
8/8 [==============================] - 0s 3ms/step - loss: 2.2147 - accuracy: 0.4922
Epoch 8/20
8/8 [==============================] - 0s 3ms/step - loss: 2.2256 - accuracy: 0.5234
Epoch 9/20
8/8 [==============================] - 0s 3ms/step - loss: 2.0726 - accuracy: 0.5547
Epoch 10/20
8/8 [==============================] - 0s 3ms/step - loss: 1.8330 - accuracy: 0.5273
Epoch 11/20
8/8 [==============================] - 0s 3ms/step - loss: 1.7762 - accuracy: 0.5898
Epoch 12/20
8/8 [==============================] - 0s 3ms/step - loss: 1.7478 - accuracy: 0.5820
Epoch 13/20
8/8 [==============================] - 0s 3ms/step - loss: 2.1825 - accuracy: 0.5664
Epoch 14/20
8/8 [==============================] - 0s 3ms/step - loss: 2.0423 - accuracy: 0.5859
Epoch 15/20
8/8 [==============================] - 0s 3ms/step - loss: 2.0127 - accuracy: 0.5938
Epoch 16/20
8/8 [==============================] - 0s 3ms/step - loss: 1.7212 - accuracy: 0.5742
Epoch 17/20
8/8 [==============================] - 0s 4ms/step - loss: 1.8876 - accuracy: 0.5312
Epoch 18/20
8/8 [==============================] - 0s 3ms/step - loss: 1.8175 - accuracy: 0.5664
Epoch 19/20
8/8 [==============================] - 0s 4ms/step - loss: 1.5964 - accuracy: 0.5664
Epoch 20/20
8/8 [==============================] - 0s 3ms/step - loss: 1.9082 - accuracy: 0.5898

In [ ]:
test_loss, test_acc = model.evaluate(X_test,y_test)

2/2 [==============================] - 0s 8ms/step - loss: 1.9097 - accuracy: 0.5938

In [ ]:
df.Veracity

0      1
1      0
2      1
3      0
4      1
      ..
315    0
316    1
317    0
318    1
319    0
Name: Veracity, Length: 320, dtype: int64

In [ ]:
vocab_size = len(tokenizer.word_index) + 1
embedding_dim = 100
max_seq_length = 163

#RNN MODEL

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout

# define the model architecture
model = Sequential()
model.add(Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=max_seq_length))
model.add(LSTM(units=64, dropout=0.2, recurrent_dropout=0.2))
model.add(Dense(units=1, activation='tanh'))

# compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# train the model
model.fit(X_train, y_train, batch_size=16, epochs=10)

Epoch 1/10
16/16 [==============================] - 5s 173ms/step - loss: 0.9150 - accuracy: 0.5352
Epoch 2/10
16/16 [==============================] - 3s 169ms/step - loss: 0.7024 - accuracy: 0.5000
Epoch 3/10
16/16 [==============================] - 4s 264ms/step - loss: 0.6999 - accuracy: 0.5391
Epoch 4/10
16/16 [==============================] - 3s 188ms/step - loss: 0.6935 - accuracy: 0.5430
Epoch 5/10
16/16 [==============================] - 3s 172ms/step - loss: 0.6895 - accuracy: 0.5352
Epoch 6/10
16/16 [==============================] - 3s 171ms/step - loss: 0.6901 - accuracy: 0.5234
Epoch 7/10
16/16 [==============================] - 3s 180ms/step - loss: 0.6869 - accuracy: 0.5312
Epoch 8/10
16/16 [==============================] - 4s 266ms/step - loss: 0.6839 - accuracy: 0.5312
Epoch 9/10
16/16 [==============================] - 3s 166ms/step - loss: 0.6861 - accuracy: 0.5352
Epoch 10/10
16/16 [==============================] - 3s 166ms/step - loss: 0.6786 - accuracy: 0.5664

In [ ]:
test_loss, test_acc = model.evaluate(X_test,y_test)

2/2 [==============================] - 0s 46ms/step - loss: 0.7101 - accuracy: 0.4375

#sent the text features for concatenated model Run

In [ ]:
'''import pickle

with open('Text_data.pkl', 'wb') as f:
    pickle.dump(concatenated_data, f)'''

"import pickle\n\nwith open('Text_data.pkl', 'wb') as f:\n    pickle.dump(concatenated_data, f)"